site_name: Core.Help
site_url: https://dappco.re
repo_url: https://github.com/Snider/Core
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Axioms of Life: agents.md
  - Core:
    - Overview: core/index.md
    - Config: core/config.md
    - Crypt: core/crypt.md
    - Display: core/display.md
    - Help: core/help.md
    - IO: core/io.md
    - Workspace: core/workspace.md

copyright: Core &copy; EUPL-1.2 &mdash; 2024 to &infin; and beyond

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  font: 
    text: "Roboto"
    code: "Roboto Mono"
  language: en
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Snider/Core
    - icon: fontawesome/solid/globe
      link: https://dappco.re

extra_css:
  - assets/stylesheets/extra.css


plugins:
  - offline:
  - privacy:
  - group:
      enabled: !ENV CI
      plugins:
        - git-revision-date-localized:
            type: timeago
            enable_creation_date: true
            fallback_to_build_date: true
            tz: Europe/London
        - git-committers:
  - group:
      enabled: !ENV INSIDERS
      plugins:
        - optimise
  - search:
      lang:
        - en
  
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
