# Minimal Goreleaser configuration for host-uk/core
# No functional changes to the codebase, just release automation.

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: core-cli
    main: ./cmd/core
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitDate }}'
    binary: core

  - id: core-gui
    # Wails GUI apps often require CGO and platform specifics; we keep a minimal build here.
    # If GUI builds need special handling, they can be adjusted later.
    main: ./cmd/core-gui
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitDate }}'
    binary: core-gui

archives:
  - id: default
    builds:
      - core-cli
      - core-gui
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE.txt
      - README.md

checksum:
  name_template: 'checksums.txt'

dockers: []

nfpms: []

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: host-uk
    name: core
  draft: false
  prerelease: auto
