version: '3'

tasks:
  build:
    summary: Builds the core executable
    cmds:
      - go build -o {{.TASKFILE_DIR}}/../bin/core {{.TASKFILE_DIR}}/..

  build:dev:
    summary: Builds and runs the core executable in development mode
    cmds:
      - go build -o {{.TASKFILE_DIR}}/../bin/core {{.TASKFILE_DIR}}/..
      - CORE_DEV_TOOLS="false" {{.TASKFILE_DIR}}/../bin/core
