// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ACTION(msg: $models.Message | null): $CancellablePromise<void> {
    return $Call.ByID(4097389530, msg);
}

export function Core(): $CancellablePromise<$models.Core | null> {
    return $Call.ByID(590325359).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RegisterAction(handler: any): $CancellablePromise<void> {
    return $Call.ByID(2751902507, handler);
}

export function RegisterActions(...handlers: any[]): $CancellablePromise<void> {
    return $Call.ByID(2391561096, handlers);
}

export function RegisterService(name: string, api: any): $CancellablePromise<void> {
    return $Call.ByID(3677749144, name, api);
}

export function Service(name: string): $CancellablePromise<any> {
    return $Call.ByID(3861253011, name);
}

// Private type creation functions
const $$createType0 = $models.Core.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
