version: '3'

includes:
  cmd: "./cmd/Taskfile.yml"

tasks:
  build:
    summary: Builds the core executable
    cmds:
      - task: cmd:build

  build:dev:
    summary: Builds the core executable
    cmds:
      - task: cmd:build:dev

  run:
    summary: Builds and runs the core executable
    cmds:
      - task: build
      - cmd: chmod +x {{.TASKFILE_DIR}}/bin/core
        platforms: [linux, darwin]
      - "{{.TASKFILE_DIR}}/bin/core {{.CLI_ARGS}}"

  sync:
    summary: Updates the public API Go files
    deps: [build]
    cmds:
      - cmd: chmod +x {{.TASKFILE_DIR}}/bin/core
        platforms: [linux, darwin]
      - "{{.TASKFILE_DIR}}/bin/core dev sync"

  test-gen:
    summary: Generates tests for the public API
    deps: [build]
    cmds:
      - cmd: chmod +x {{.TASKFILE_DIR}}/bin/core
        platforms: [linux, darwin]
      - "{{.TASKFILE_DIR}}/bin/core dev test-gen"
